#define LABEL_PMED_MESSAGE "pmed_message"
#define ATTRIBUT_PMED_MESSAGE_SENDERID "senderid"

#define LABEL_PMED_PATIENT "pmed_patient"
#define ATTRIBUT_PMED_PATIENT_PATIENTID "patientid"

#define LABEL_PMED_ADMINDATA "pmed_admindata"
#define ATTRIBUT_PMED_ADMINDATA_SEXE "sexe"
#define ATTRIBUT_PMED_ADMINDATA_DATE_NAISSANCE "naissance"
#define ATTRIBUT_PMED_ADMINDATA_CODE_POSTAL "code_post"

#define LABEL_PMED_HEALTHDATA "pmed_healthdata"

#define LABEL_PMED_PROBLEM "pmed_problem"
#define ATTRIBUT_PMED_PROBLEM_PROBLEMID "problemid"

#define LABEL_PMED_PROBLEM_EVENT "pmed_problem_event"
#define ATTRIBUT_PMED_PROBLEM_EVENT_DATE "date"
#define ATTRIBUT_PMED_PROBLEM_EVENT_TYPE "type"
#define ATTRIBUT_PMED_PROBLEM_EVENT_RELATED_PB_ID "related_pb_id"
#define ATTRIBUT_PMED_PROBLEM_EVENT_TITLE "title"
#define ATTRIBUT_PMED_PROBLEM_EVENT_IMPORTANT "important"

#define LABEL_PMED_CONTACT "pmed_contact"
#define ATTRIBUT_PMED_CONTACT_CONTACTID "contactid"
#define ATTRIBUT_PMED_CONTACT_TYPE_PRINCIPE "type_principe"
#define ATTRIBUT_PMED_CONTACT_DATE "date"

#define LABEL_PMED_CONTACT_TYPE "pmed_contact_type"
#define ATTRIBUT_PMED_CONTACT_TYPE_CONDITIONS "conditions"
#define ATTRIBUT_PMED_CONTACT_TYPE_RENDEZ_VOUS "rendez_vous"

#define LABEL_PMED_CONTACTELEMENT "pmed_contactelement"
#define ATTRIBUT_PMED_CONTACTELEMENT_CONTACTELEMENTID "contactelementid"
#define ATTRIBUT_PMED_CONTACTELEMENT_PROBLEMID "problemid"

#define LABEL_PMED_CONTACTCODE "pmed_contactcode"
#define ATTRIBUT_PMED_CONTACTCODE_POSITION "position"
#define ATTRIBUT_PMED_CONTACTCODE_CLASSIFICATION "classification"
#define ATTRIBUT_PMED_CONTACTCODE_CODE "code"
#define ATTRIBUT_PMED_CONTACTCODE_CLASSIFICATION_BIS "classification_bis"
#define ATTRIBUT_PMED_CONTACTCODE_CODE_BIS "code_bis"

#define LABEL_PMED_CONTACTTREE				"pmed_contacttree"
#define ATTRIBUT_PMED_CONTACTTREE_POSITION		"position"

#define LABEL_PMED_CONTACTNODE				"pmed_contactnode"
#define ATTRIBUT_PMED_CONTACTNODE_LOCALISATION "codeloc"
#define ATTRIBUT_PMED_CONTACTNODE_LEXIQUE      "lexique"
#define ATTRIBUT_PMED_CONTACTNODE_COMPLEMENT   "complement"
#define ATTRIBUT_PMED_CONTACTNODE_CERTITUDE    "certitude"
#define ATTRIBUT_PMED_CONTACTNODE_PLURIEL      "pluriel"
#define ATTRIBUT_PMED_CONTACTNODE_UNIT         "unit"

